name: Garmin to Google Sheets Sync

on:
  schedule:
    # 07:13 UTC entspricht 09:13 Uhr (Sommerzeit Deutschland)
    # 17:13 UTC entspricht 19:13 Uhr (Sommerzeit Deutschland)
    - cron: '13 7,17 * * *'
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install --upgrade --no-cache-dir -r requirements.txt
      
      - name: Run sync script
        env:
          GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
          GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GARMIN_SESSION_BASE64: ${{ secrets.GARMIN_SESSION_BASE64 }}
          GARMIN_TOKENS: ${{ secrets.GARMIN_TOKENS }}
        run: python sync_garmin.py
